### ISSUE TITLE
qq群也可以用吗

### ISSUE THREAD

**Issue by liuzj288** [GC-ZF/nonebot_plugin_firexN#1]

**Comment by GC-ZF** [comment]
插件的目的就是QQ续火花，没有此功能计划。给你另外写了一个，但不打包，因为功能不是本仓库的初衷，之后我会pr给群管插件的作者，单独的消息推送功能等一下单独发给你

**Comment by GC-ZF** [comment]
> _No description provided._

插件的初衷是续火花而不是群聊定时推送，所以不打算将群聊功能加在pip安装中，如果需要请看仓库首页更新，已添加群聊使用说明
